### ISSUE TITLE
recipe issue 

### ISSUE THREAD

**Issue by pbanj** [RoboTricker/Transport-Pipes#46]
every time i try to change the recipe to add stuff it resets the config file for it

here is the default config as you know
```
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '280:0'
```

if i change it to say this

```
    shape:
    - ggh
    - gbg
    - hgg
    ingredients:
      g: '20:0'
      b: '280:0'
      h: '264'
```

it will reset the config i have tried using other letter than h and it give the same result. i can change the default items but it wont let me add new ones.

**Comment by RoboTricker** [comment]
can give post the whole recipes.yml file please?

**Comment by pbanj** [comment]
```
recipe:
  colored:
    type: shaped
    amount: 4
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '280:0'
    white:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:15'
    blue:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:4'
    red:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:1'
    yellow:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:11'
    green:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:2'
    black:
      type: shapeless
      amount: 1
      ingredients:
      - pipe
      - '351:0'
  golden:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '41:0'
  iron:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '42:0'
  ice:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '80:0'
  void:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '49:0'
  extraction:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '5'
  crafting:
    type: shaped
    amount: 1
    shape:
    - ggx
    - gbg
    - xgg
    ingredients:
      g: '20:0'
      b: '58:0'
  wrench:
    type: shaped
    amount: 1
    shape:
    - xrx
    - rsr
    - xrx
    ingredients:
      r: '331:0'
      s: '280:0'

```
